"""wishlist

Revision ID: ba5eb1cd8bf6
Revises: e366cac4754c
Create Date: 2026-08-17 16:49:53.755145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba5eb1cd8bf6'
down_revision: Union[str, Sequence[str], None] = 'e366cac4754c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_favorite_user_product')
    )
    op.create_index(op.f('ix_wishlist_product_id'), 'wishlist', ['product_id'], unique=False)
    op.create_index(op.f('ix_wishlist_user_id'), 'wishlist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wishlist_user_id'), table_name='wishlist')
    op.drop_index(op.f('ix_wishlist_product_id'), table_name='wishlist')
    op.drop_table('wishlist')
    # ### end Alembic commands ###
